version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./app:/app
  db:
    image: mysql/mysql-server:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=medcooperative
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password 
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  dbdata: {}